### ISSUE TITLE
能否实现自动投送amiboo的功能

### ISSUE THREAD

**Issue by winniediandian** [EasyConNS/EasyCon#15]
在ns需要刷amiboo的时候，easycon可以在脚本里投送amiboo数据给ns，如果很麻烦，就算啦~

**Comment by elmagnificogi** [comment]
理论可以，作为一个Feature后续看是否有可能实现吧

不过还有一点，amibo我们手上也不全，可能需要有人赞助一些稀有的？

**Comment by jiguanglizipao** [comment]
可以从这里找到 amiibo
https://hax0kartik.github.io/amiibo-generator/

**Comment by elmagnificogi** [comment]
已经实现
